# Generated by Django 2.2.6 on 2019-10-20 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='geodata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geodata_pid', models.IntegerField(verbose_name='省份编号')),
                ('geodata_order', models.IntegerField(verbose_name='爆发顺序')),
                ('geodata_sdate', models.CharField(max_length=50, verbose_name='确诊日期')),
                ('geodata_province', models.CharField(max_length=20, verbose_name='省份')),
                ('geodata_city', models.CharField(max_length=40, verbose_name='城市')),
                ('geodata_county', models.CharField(max_length=100, verbose_name='区县')),
                ('geodata_place', models.CharField(max_length=100, verbose_name='发生地')),
                ('geodata_farmsize', models.IntegerField(verbose_name='养殖场规模')),
                ('geodata_totalnum', models.IntegerField(verbose_name='发病数')),
                ('geodata_deathnum', models.IntegerField(verbose_name='死亡时')),
                ('geodata_oie', models.IntegerField(verbose_name='OIE确诊数')),
                ('geodata_edate', models.CharField(max_length=50, verbose_name='解除死亡时间')),
            ],
        ),
    ]
