# Generated by Django 2.2.6 on 2019-10-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geodata',
            name='geodata_deathnum',
            field=models.IntegerField(verbose_name='死亡数'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='geodata_oie',
            field=models.IntegerField(verbose_name='OIE'),
        ),
    ]
