# Generated by Django 2.2.6 on 2019-10-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20191020_2027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geodata',
            name='geodata_city',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='geodata_county',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='geodata_edate',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='geodata_pid',
        ),
        migrations.RemoveField(
            model_name='geodata',
            name='geodata_province',
        ),
        migrations.AddField(
            model_name='geodata',
            name='geodata_coordinates',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='坐标'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='geodata_place',
            field=models.CharField(max_length=255, verbose_name='发生地'),
        ),
        migrations.AlterField(
            model_name='geodata',
            name='geodata_sdate',
            field=models.DateField(verbose_name='确诊日期'),
        ),
    ]
