# Generated by Django 2.2.6 on 2019-10-22 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20191022_2007'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='geodata',
            table='demo_data',
        ),
    ]
